function probe_first_slice(workspace_path, out_path)
%PROBE_FIRST_SLICE  Measure the one step a conditional ENSO run is not masked.
%
%   The conditional scripts build their observation-noise inverse in two
%   passes: a pseudoinverse fills slice one, then a single diagonal entry is
%   overwritten across every slice. Slice one therefore keeps the
%   pseudoinverse's other entries, and the filter consumes slice one at j = 2.
%   Every later step assimilates the target channel alone; the first step does
%   not.
%
%   aciR's `aci_conditional()` masks the non-target block at every step,
%   including the first. Whether that matters is a question about a number, and
%   this measures it rather than arguing it.
%
%   The measurement changes no code. `S_x(:, :, 1)` is diagonal in this model,
%   so zeroing its non-target entries makes the pseudoinverse of the slice-one
%   Grammian vanish off the target block (which is exactly the weight aciR
%   supplies), and the SAME byte-verified extract is then run twice, once on
%   each input.

w = load(workspace_path);

[m_ref, c_ref] = ref_enso_h_W_filter(w.T_C, w.T_E, w.I, w.h_W, w.L_x, w.L_y, ...
                                     w.f_x, w.f_y, w.S_x, w.sigma_C, ...
                                     w.sigma_h, w.N, w.dt);

S_x_masked = w.S_x;
S_x_masked(2, 2, 1) = 0;
S_x_masked(3, 3, 1) = 0;
[m_mask, c_mask] = ref_enso_h_W_filter(w.T_C, w.T_E, w.I, w.h_W, w.L_x, ...
                                       w.L_y, w.f_x, w.f_y, S_x_masked, ...
                                       w.sigma_C, w.sigma_h, w.N, w.dt);

d_mean = abs(m_ref - m_mask);
d_cov = abs(c_ref - c_mask);
scale = max(abs(m_ref));

% Whether this is a transient or a standing offset is the question that decides
% whether the two constructions can be graded against each other at all, so the
% decay is measured rather than assumed. `settle` is the last step at which the
% difference still exceeds a level; a small number means the filter forgets.
settle = @(d, level) max([0, find(d > level, 1, 'last')]);

T = table( ...
    {'filter_mean'; 'filter_cov'}, ...
    [numel(m_ref); numel(c_ref)], ...
    [d_mean(2); d_cov(2)], ...
    [max(d_mean); max(d_cov)], ...
    [settle(d_mean, 1e-6); settle(d_cov, 1e-6)], ...
    [settle(d_mean, 1e-12); settle(d_cov, 1e-12)], ...
    [find(d_mean > 0, 1, 'last'); find(d_cov > 0, 1, 'last')], ...
    [scale; max(abs(c_ref))], ...
    'VariableNames', {'quantity', 'n', 'step2_abs', 'max_abs', ...
                      'last_above_1e6', 'last_above_1e12', ...
                      'last_differing_step', 'scale'});
writetable(T, out_path);

fprintf(['first-slice mask: filter_mean differs by %.6g at step 2, worst ' ...
         '%.6g, last above 1e-6 at step %d, above 1e-12 at %d, non-zero to ' ...
         '%d of %d (signal scale %.6g)\n'], ...
        d_mean(2), max(d_mean), settle(d_mean, 1e-6), ...
        settle(d_mean, 1e-12), find(d_mean > 0, 1, 'last'), numel(m_ref), ...
        scale);
fprintf(['first-slice mask: filter_cov  differs by %.6g at step 2, worst ' ...
         '%.6g, last above 1e-6 at step %d, above 1e-12 at %d\n'], ...
        d_cov(2), max(d_cov), settle(d_cov, 1e-6), settle(d_cov, 1e-12));
fprintf('wrote %s\n', out_path);

end
