# -- S4: run both implementations on one dataset and compare -------------------
#
# The side-by-side proper. One bundle goes to the extracted reference kernels
# and to aciR, and every quantity they both produce is compared against a
# tolerance declared in advance.
#
# Declared in advance matters. A tolerance chosen after seeing the difference
# is not a test, it is a description; and a pair that agrees far BETTER than
# its declared class is reported too, because that usually means the comparison
# is not reaching the code it claims to reach.

#' Build the dataset bundles this harness ships with.
#'
#' @param root Directory to write bundles into.
#'
#' @returns A character vector of bundle paths.
build_datasets <- function(root = file.path("oracle", "parity", "datasets")) {
  paths <- character(0)

  # ---- 1. the reference's own signal, truncated ------------------------------
  #
  # The published dyad run, cut to a length whose quadratic sections are
  # affordable. Truncation is sound because both sides then run on the SAME
  # 3001-step record: the comparison is aciR against MATLAB, not against the
  # published figure.
  regrade <- file.path("oracle", "parity", "reports",
                       "regrade_dyad_full_signal.csv")
  run_matlab(
    c(
      paste0(
        "[x, y, L_x, f_x, f_y, L_y, Sx_1, Sx_2, Sy_1, Sy_2, N, dt, T, gamma, ",
        "d_x, d_y, F_x, F_y, sigma_x, sigma_y] = ref_dyad_setup_and_signals();"
      ),
      "n = 3001;",
      paste0(
        "writetable(table(x(1:n)', L_x(1:n)', f_x(1:n)', f_y(1:n)', ",
        "'VariableNames', {'x','L_x','f_x','f_y'}), ",
        as_matlab_path(regrade), ");"
      ),
      "fprintf('signal head written\\n');"
    ),
    label = "dataset_dyad"
  )
  arrays <- utils::read.csv(regrade, stringsAsFactors = FALSE)
  path <- file.path(root, "dyad_reference_head")
  write_dataset(
    path,
    list(
      Name = "dyad_reference_head",
      Description = paste(
        "First 3001 steps of the published dyad signal, generated by the",
        "reference's own rng(333) through ref_dyad_setup_and_signals."
      ),
      Provenance = "dyad_interaction_model.m lines 48-125, unmodified",
      Kind = "scalar", N = 3000L, dt = 0.001,
      CIRStart = 0.5, CIREnd = 1.5,
      mu0 = 2, R0 = 0.1,
      L_y = -0.5, Sx_1 = 0.5, Sx_2 = 0, Sy_1 = 0, Sy_2 = 1
    ),
    arrays
  )
  paths <- c(paths, path)

  # ---- 2. a genuinely arbitrary record, with CROSS-NOISE ---------------------
  #
  # The point of this one is the noise cross-covariance. The dyad has Sx_2 =
  # Sy_1 = 0, so S_yoS_x vanishes and every term it multiplies is dead on the
  # published fixture -- graded, reachable, and multiplied by zero. Here the
  # feedbacks are chosen so S_yoS_x = 0.5, and the components have nothing to
  # do with the dyad's quadratic nonlinearity.
  set.seed(20260814L)
  n <- 2000L
  dt <- 0.002
  t <- seq.int(0L, n) * dt
  x <- cumsum(c(0.7, stats::rnorm(n, sd = 0.05)))
  arbitrary <- data.frame(
    x = x,
    L_x = 0.8 + 0.35 * sin(3 * t),
    f_x = 0.2 * cos(2 * t) - 0.1 * x,
    f_y = 0.45 - 0.15 * x^2
  )
  path <- file.path(root, "arbitrary_cross_noise")
  write_dataset(
    path,
    list(
      Name = "arbitrary_cross_noise",
      Description = paste(
        "A record unrelated to any model in the reference: a random-walk",
        "observation with trigonometric components and a NON-ZERO noise",
        "cross-covariance (S_yoS_x = 0.5), which the dyad fixture cannot",
        "exercise because its Sx_2 and Sy_1 are both zero."
      ),
      Provenance = "generated by tools/compare.R, set.seed(20260814)",
      Kind = "scalar", N = n, dt = dt,
      CIRStart = 0.5, CIREnd = 2.0,
      mu0 = 0.3, R0 = 0.1,
      L_y = -1.3, Sx_1 = 0.5, Sx_2 = 0.3, Sy_1 = 0.4, Sy_2 = 1
    ),
    arbitrary
  )
  paths <- c(paths, path)

  paths
}

#' Run one dataset through both implementations and compare.
#'
#' @param dataset_dir Path to a bundle.
#' @param tolerances Named numeric vector of declared relative tolerances.
#' @param do_lags Logical. Also compare the online smoother at three lags.
#'
#' @returns A data frame with one row per quantity.
compare_dataset <- function(dataset_dir,
                            tolerances = c(
                              filter_mean = 1e-12, filter_cov = 1e-12,
                              smoother_mean = 1e-12, smoother_cov = 1e-12,
                              ACI_metric = 1e-11, E_j = 1e-12, F_j = 1e-12
                            ),
                            do_lags = TRUE) {
  name <- basename(dataset_dir)
  out <- file.path("oracle", "parity", "reports",
                   sprintf("matlab_%s.csv", name))
  dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)

  run_matlab(
    sprintf("parity_run_scalar(%s, %s, %s);",
            as_matlab_path(dataset_dir), as_matlab_path(out),
            if (do_lags) "true" else "false"),
    label = sprintf("run_%s", name)
  )
  reference <- utils::read.csv(out, stringsAsFactors = FALSE)

  dataset <- read_dataset(dataset_dir)
  meta <- dataset$meta
  comp <- dataset_components(dataset)
  x <- dataset$arrays$x

  filt <- aciR::aci_filter(x, comp, meta$dt, mu0 = meta$mu0, R0 = meta$R0)
  smooth <- aciR::aci_smoother(x, comp, meta$dt, filt)
  metric <- aciR::aci_metric(filt, smooth)
  aux <- getFromNamespace(".aci_online_aux", "aciR")(x, comp, meta$dt, filt)

  ours <- list(
    filter_mean = filt$mean, filter_cov = filt$cov,
    smoother_mean = smooth$mean, smoother_cov = smooth$cov,
    ACI_metric = metric, E_j = aux$E, F_j = aux$F
  )

  rows <- lapply(names(ours), function(quantity) {
    theirs <- reference[[quantity]]
    mine <- ours[[quantity]]
    .compare_vectors(quantity, mine, theirs, tolerances[[quantity]], name)
  })

  if (isTRUE(do_lags)) {
    for (lag in c(0L, 25L, meta$N + 1L)) {
      lag_path <- file.path(
        dirname(out),
        sprintf("%s_online_lag%d.csv", sub("\\.csv$", "", basename(out)), lag)
      )
      if (!file.exists(lag_path)) {
        next
      }
      theirs <- utils::read.csv(lag_path, stringsAsFactors = FALSE)
      r_lag <- if (lag > meta$N) Inf else lag
      online <- aciR::aci_online_smoother(x, comp, meta$dt, filt, lag = r_lag)
      rows <- c(rows, list(
        .compare_vectors(sprintf("online_mean(lag=%s)", r_lag), online$mean,
                         theirs$online_mean, 1e-11, name),
        .compare_vectors(sprintf("online_cov(lag=%s)", r_lag), online$cov,
                         theirs$online_cov, 1e-11, name)
      ))
    }
  }

  if (isTRUE(do_lags)) {
    rows <- c(rows, .compare_cir(dirname(out), basename(out), dataset, comp,
                                 filt, x))
  }

  do.call(rbind, rows)
}

# -- causal influence range ----------------------------------------------------
#
# The quantity with the most designed differences between the two, so the
# comparison has to be set up rather than merely run:
#
#  * the reference fixes 513 logarithmic thresholds inside its own range where
#    aciR defaults to 129, so aciR is handed the reference's own grid;
#  * the reference guards the end of the record with an ABSOLUTE
#    `lookahead_tolerance` of 0.6 time units; aciR uses a `margin` FRACTION of
#    what remains after each reporting time. The two therefore exclude
#    different sets of times, and the comparison is restricted to those both
#    consider resolved -- with the counts each excluded reported rather than
#    quietly dropped.
.compare_cir <- function(report_dir, stem, dataset, comp, filt, x) {
  base <- sub("\\.csv$", "", stem)
  cir_path <- file.path(report_dir, sprintf("%s_cir.csv", base))
  eps_path <- file.path(report_dir, sprintf("%s_cir_epsilon.csv", base))
  sub_path <- file.path(report_dir, sprintf("%s_cir_subjective.csv", base))
  if (!file.exists(cir_path)) {
    return(list())
  }
  meta <- dataset$meta
  theirs <- utils::read.csv(cir_path, stringsAsFactors = FALSE)
  epsilon <- utils::read.csv(eps_path, header = FALSE)[[1L]]
  their_subjective <- as.matrix(utils::read.csv(sub_path, header = FALSE))

  ours <- aciR::aci_cir(
    x, comp, meta$dt, filt = filt, window = theirs$index,
    epsilon = epsilon, margin = 0.1
  )

  # ---- the horizon divergence ------------------------------------------------
  #
  # The reference computes over first_idx..last_idx but PLOTS only to
  # time_end_plot; the trailing `lookahead_tolerance` worth of reporting times
  # is a guard it computes and discards, because its own values there are
  # truncated. Comparing over the guard region compares against numbers the
  # reference does not stand behind, so the two regions are reported apart.
  #
  # Within the reported region the peak agrees to machine precision. The
  # objective and subjective ranges do NOT, and the cause is the same
  # mechanism: for each reporting time the reference integrates and searches
  # the lagged sequence only as far as last_idx, where aciR runs to the end of
  # the record. aciR therefore sees more of the tail, and reports a larger
  # integral and a longer range. Neither is a coding error; aciR's is the more
  # faithful reading of the definition and the reference's is a memory-driven
  # truncation (its RE_metric is plot_len squared). But it does mean aciR
  # cannot currently reproduce the published CIR figures, because it has no
  # argument with which to adopt the reference's horizon.
  plot_end <- round(as.numeric(meta$CIREnd) / meta$dt) + 1L
  reported <- theirs$index <= plot_end
  guard <- !reported

  out <- list(
    .compare_vectors("cir_peak (reported region)", ours$peak[reported],
                     theirs$peak[reported], 1e-11, meta$Name),
    .compare_vectors("cir_peak (reference guard region)", ours$peak[guard],
                     theirs$peak[guard], 1e-11, meta$Name)
  )

  keep <- reported & !ours$saturated & is.finite(theirs$objective)
  out <- c(out, list(.compare_vectors(
    "cir_objective (reported region)", ours$objective[keep],
    theirs$objective[keep], 1e-11, meta$Name
  )))

  # The reference's subjective grid is ordered by its own descending exponent
  # vector; aciR orders by the epsilon it was handed. Both are put on ascending
  # epsilon before comparison.
  our_subjective <- ours$subjective[order(epsilon), reported, drop = FALSE]
  their_ordered <- their_subjective[order(epsilon), reported, drop = FALSE]
  both <- is.finite(our_subjective) & is.finite(their_ordered)
  out <- c(out, list(.compare_vectors(
    "cir_subjective (reported region)", our_subjective[both],
    their_ordered[both], 1e-11, meta$Name
  )))

  message(sprintf(
    paste0(
      "   CIR: %d times computed, %d reported, %d in the reference's guard; ",
      "aciR marked %d saturated; subjective %d of %d cells compared"
    ),
    length(ours$peak), sum(reported), sum(guard), sum(ours$saturated),
    sum(both), length(both)
  ))
  out
}

# -- the comparison criterion --------------------------------------------------
#
# `|a - b| <= atol + rtol * |b|`, elementwise, rather than relative error
# alone.
#
# The absolute term is not a loophole, it is the part a purely relative
# criterion is missing. A relative error divides by the value, so wherever a
# series crosses zero it divides by nothing in particular and reports a large
# number for a difference that is small on every scale that matters. This
# harness met that on its first run: the online smoothed mean at full lag
# passed through -1.7e-4 at one step out of 3001 -- the only point in the
# series below 1e-3, against a median of 0.86 -- and a 7e-15 absolute
# difference there, some thirty units in the last place of the order-one
# operands it is a cancellation of, registered as a relative error of 4e-11.
#
# So the relative tolerance is NOT relaxed to accommodate it. It stays where it
# was; the absolute floor is added underneath, and both numbers stay in the
# report so a reader can see which term carried the verdict.

.compare_vectors <- function(quantity, mine, theirs, tolerance, dataset,
                             atol = 1e-12) {
  n <- min(length(mine), length(theirs))
  if (length(mine) != length(theirs)) {
    return(data.frame(
      dataset = dataset, quantity = quantity, n = n,
      max_abs = NA_real_, max_rel = NA_real_, rtol = tolerance, atol = atol,
      headroom = NA_real_,
      verdict = sprintf("LENGTH %d vs %d", length(mine), length(theirs)),
      stringsAsFactors = FALSE
    ))
  }
  # An empty comparison is not a pass. `max(numeric(0))` is -Inf, which sails
  # under every threshold and reports "ok" for having compared nothing -- the
  # same vacuous-grading failure this harness exists to detect, reproduced
  # inside the checker. It is a failure, and it is named.
  if (n == 0L) {
    return(data.frame(
      dataset = dataset, quantity = quantity, n = 0L,
      max_abs = NA_real_, max_rel = NA_real_, rtol = tolerance, atol = atol,
      headroom = NA_real_, verdict = "EMPTY -- nothing compared",
      stringsAsFactors = FALSE
    ))
  }

  mine <- mine[seq_len(n)]
  theirs <- theirs[seq_len(n)]
  absolute <- abs(mine - theirs)
  scale <- pmax(abs(mine), abs(theirs))
  relative <- ifelse(scale > 0, absolute / scale, 0)

  bound <- atol + tolerance * scale
  worst <- max(absolute / bound)

  data.frame(
    dataset = dataset, quantity = quantity, n = n,
    max_abs = max(absolute), max_rel = max(relative),
    rtol = tolerance, atol = atol,
    # How much of the permitted budget the worst element used. A reviewer can
    # tell a comfortable pass from one that squeaked through.
    headroom = 1 / worst,
    verdict = if (worst > 1) {
      "EXCEEDS"
    } else if (max(absolute) == 0) {
      # Two implementations, two languages, two compilers: bit-identical output
      # is not a triumph, it is a smell. It usually means one side did not run,
      # or both read the same file.
      "SUSPECT-EXACT"
    } else {
      "ok"
    },
    stringsAsFactors = FALSE
  )
}
