# driving MATLAB from R --------------------------------------------------------
#
# `matlab -batch` accepts one command, so anything with structure has to reach
# it as a file. Every MATLAB step in this harness therefore goes through
# `run_matlab()`, which writes the code to a scratch script and runs that. The
# script is kept on failure, because a MATLAB error message without the code
# that produced it is not diagnosable.

matlab_binary <- function() {
  candidates <- c(
    Sys.getenv("ACIR_MATLAB", ""),
    "/Applications/MATLAB_R2025b.app/bin/matlab",
    "/Applications/MATLAB_R2024b.app/bin/matlab",
    unname(Sys.which("matlab"))
  )
  candidates <- candidates[nzchar(candidates)]
  found <- candidates[file.exists(candidates)]
  if (length(found) == 0L) {
    stop(
      paste0(
        "no MATLAB binary found. Set ACIR_MATLAB to its path, e.g.\n",
        "  Sys.setenv(ACIR_MATLAB = \"/Applications/MATLAB_R2025b.app/bin/matlab\")"
      ),
      call. = FALSE
    )
  }
  found[1L]
}

#' Run MATLAB code, returning its output.
#'
#' @param code Character vector of MATLAB statements, one per element.
#' @param label Character scalar. Used to name the scratch script.
#' @param quiet Logical. Drop the reference scripts' progress-bar lines, which
#'   are carriage-return animations and unreadable in a log.
#'
#' @returns A character vector of output lines, invisibly. Errors when MATLAB
#'   exits non-zero.
run_matlab <- function(code, label = "step", quiet = TRUE) {
  scratch <- file.path("tools", "oracle", "parity", "workspaces", ".scratch")
  dir.create(scratch, recursive = TRUE, showWarnings = FALSE)
  script <- file.path(scratch, sprintf("parity_%s.m", label))

  # The harness helpers, the generated extracts, and the reference directory.
  # The last is needed because the extracted slices call the reference's own
  # auxiliaries (simps, progress_bar), which we neither vendor nor reimplement.
  search_path <- c(
    file.path("tools", "oracle", "parity", "matlab"),
    file.path("tools", "oracle", "parity", "matlab", "extracted"),
    "matlab_reference",
    "matlab_reference_fbcir",
    "matlab_reference_enkbs",
    file.path("matlab_reference_enkbs", "model discovery")
  )
  search_path <- search_path[dir.exists(search_path)]

  writeLines(c(
    "% Generated by oracle/parity/tools/matlab.R -- safe to delete.",
    sprintf("addpath('%s');", normalizePath(search_path)),
    code
  ), script)

  output <- suppressWarnings(system2(
    matlab_binary(),
    args = c("-batch", shQuote(sprintf("run('%s')", normalizePath(script)))),
    stdout = TRUE, stderr = TRUE
  ))
  status <- attr(output, "status")

  if (isTRUE(quiet)) {
    output <- output[!grepl("^(Online Smoother|Calculation of the CIRs)", output)]
    output <- output[nzchar(trimws(output))]
  }
  if (!is.null(status) && status != 0L) {
    stop(
      sprintf(
        "MATLAB exited %d. Script kept at %s\n%s",
        status, script, paste(utils::tail(output, 30L), collapse = "\n")
      ),
      call. = FALSE
    )
  }
  invisible(output)
}

# Quote an R character vector as a MATLAB cell array of strings.
as_matlab_cell <- function(x) {
  sprintf("{%s}", paste(sprintf("'%s'", gsub("'", "''", x)), collapse = ", "))
}

# Quote an R string as an absolute MATLAB path literal. Absolute because a
# relative path is interpreted against MATLAB's working directory, which is not
# reliably R's. Normalising the directory rather than the whole path lets this
# name a file that does not exist yet, which is the usual case for an output.
as_matlab_path <- function(x) {
  directory <- normalizePath(dirname(x), mustWork = FALSE)
  sprintf("'%s'", file.path(directory, basename(x)))
}
