#' aciR: Assimilative Causal Inference for Conditional Gaussian Nonlinear
#' Systems
#'
#' The aciR package implements assimilative causal inference (ACI) for
#' conditional Gaussian nonlinear systems (CGNS). A CGNS pairs an observed
#' signal with an unobserved component whose conditional statistics, given the
#' observed path, are Gaussian and available in closed form.
#'
#' Most analyses need three calls. [aci_dyad_model()] or [aci_cgns_model()]
#' builds an `aci_model`, [aci_simulate()] draws a realisation of it, and
#' [aci()] runs the whole workflow on an observed signal and returns an `aci`
#' object with [summary.aci()], [plot.aci()] and [as.data.frame.aci()]
#' methods.
#'
#' Beneath that sits the numerical core, comprising the forward filter
#' ([aci_filter()]), the backward smoother ([aci_smoother()]) and the
#' relative-entropy causal-information metric ([aci_metric()]). The three are
#' written against a general CGNS components list rather than a specific model,
#' so they apply to any conditional Gaussian system. [aci_components] documents
#' that schema and [aci_dyad_components()] is its worked example.
#'
#' The numerical core is graded against fixtures generated by an independent
#' MATLAB harness reproducing the deterministic core of the reference
#' implementation. The *Validation and the independent oracle* vignette
#' records the design, the provenance and the observed agreement; the
#' *Assumptions and interpretation* vignette states what the method assumes and
#' what an ACI peak does and does not support.
#'
#' The method reimplemented here is due to Andreou, Chen and Bollt (2026).
#'
#' @references
#' Andreou, M., Chen, N. and Bollt, E. (2026). Assimilative causal inference.
#' *Nature Communications*, 17, 1854. \doi{10.1038/s41467-026-68568-0}
#'
#' @keywords internal
"_PACKAGE"
